language: php

php:
  - 7.2
  - 7.3

env:
  global:
    - COMPOSER_FLAGS=""
  matrix:
    - LARAVEL=5.8.*
    - LARAVEL=6.*
    - COMPOSER_FLAGS="--prefer-lowest" LARAVEL='5.8.*' TESTBENCH='3.8.*'
    - COMPOSER_FLAGS="--prefer-lowest" LARAVEL='6.*' TESTBENCH='4.0.*'

before_install:
  - travis_retry composer self-update

before_script:
  - travis_retry composer require "laravel/framework=${LARAVEL}" "orchestra/testbench:${TESTBENCH}" --prefer-source --no-interaction --no-suggest
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
  - ./vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
